### ISSUE TITLE
About code release

### ISSUE THREAD

**Issue by torukk123** [TomorrowJW/MECS-Net-COD#1]
I recently read your paper and found it to be very intriguing.
The work you have done is truly innovative.
I appreciate the time and effort you have already put into publishing your research. If you have plans to release the code publicly soon, I would also appreciate knowing the timeline.
Thank you very much for your time and consideration

**Comment by TomorrowJW** [comment]
Thanks for your attention, I will release the code and experimental results here next week. (感谢关注，下周我将释放代码和实验结果到这，谢谢对我工作的肯定).

**Comment by cenchaojun** [comment]
also wait

**Comment by TomorrowJW** [comment]
代码和测试结果和相关权重已经上传，谢谢关注，记得引用我们的工作哦！
