### ISSUE TITLE
师兄，有没有搜集到比较好的可视化代码？

### ISSUE THREAD

**Issue by WkangLiu** [TomorrowJW/MECS-Net-COD#2]
看您在FSNet里有提问，所以来问问有没有好用的。
另外[SARNet](https://github.com/Haozhe-Xing/SARNet)公布了一个可视化代码（今天刚公布），可以参考。

**Comment by TomorrowJW** [comment]
没，感觉那个好繁琐，自己找了个网上的测试成功了

**Comment by WkangLiu** [comment]
好嘞，期待您好的工作

**Comment by TomorrowJW** [comment]
给一个小星星啊，哈哈

**Comment by WkangLiu** [comment]
木的问题哈哈哈
